services:
    backend:
        restart: always
        build: ./backend
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        env_file:
            - .env.dev
        volumes:
            - ./backend/logs/:/usr/src/backend/logs/
            - ./backend:/usr/src/backend/
        networks:
            - backend_network
        depends_on:
            db:
                condition: service_healthy
    telegram_app:
        restart: always
        build: ./telegram_app
        command: python main.py
        env_file:
            - ./.env.dev
        networks:
            - backend_network
        depends_on:
            - backend
    db:
        image: postgres:14.5
        env_file:
            - .env.dev.db
        volumes:
            - db_data:/var/lib/postgresql/data/
        networks:
            - backend_network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 3s
            timeout: 5s
            retries: 5

volumes:
    db_data:

networks:
    backend_network:
