# Generated by Django 4.1.1 on 2024-06-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
